### ISSUE TITLE
Can't build on Ubuntu 17.04

### ISSUE THREAD

**Issue by jimmsta** [mborgerson/fatx#3]
When I try making this on Ubuntu 17.04 using the instructions provided, I get this set of errors:

> [ 83%] Built target libfatxfs
[ 91%] Building C object CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o
In file included from /home/xboxen/fatx/src/fatxfs_fuse.c:31:0:
/usr/include/fuse/fuse.h:444:54: error: array type has incomplete element type ‘struct timespec’
  int (*utimens) (const char *, const struct timespec tv[2]);
                                                      ^~
/usr/include/fuse/fuse.h:444:45: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  int (*utimens) (const char *, const struct timespec tv[2]);
                                             ^~~~~~~~
/usr/include/fuse/fuse.h:867:29: error: array type has incomplete element type ‘struct timespec’
       const struct timespec tv[2]);
                             ^~
/usr/include/fuse/fuse.h:867:20: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
       const struct timespec tv[2]);
                    ^~~~~~~~
CMakeFiles/fatxfs.dir/build.make:62: recipe for target 'CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o' failed
make[2]: *** [CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/fatxfs.dir/all' failed
make[1]: *** [CMakeFiles/fatxfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mborgerson** [comment]
Fixed.
