### PR TITLE
fix build on current systems

### LINKED ISSUE #3: Can't build on Ubuntu 17.04
When I try making this on Ubuntu 17.04 using the instructions provided, I get this set of errors:

> [ 83%] Built target libfatxfs
[ 91%] Building C object CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o
In file included from /home/xboxen/fatx/src/fatxfs_fuse.c:31:0:
/usr/include/fuse/fuse.h:444:54: error: array type has incomplete element type ‘struct timespec’
  int (*utimens) (const char *, const struct timespec tv[2]);
                                                      ^~
/usr/include/fuse/fuse.h:444:45: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  int (*utimens) (const char *, const struct timespec tv[2]);
                                             ^~~~~~~~
/usr/include/fuse/fuse.h:867:29: error: array type has incomplete element type ‘struct timespec’
       const struct timespec tv[2]);
                             ^~
/usr/include/fuse/fuse.h:867:20: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
       const struct timespec tv[2]);
                    ^~~~~~~~
CMakeFiles/fatxfs.dir/build.make:62: recipe for target 'CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o' failed
make[2]: *** [CMakeFiles/fatxfs.dir/src/fatxfs_fuse.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/fatxfs.dir/all' failed
make[1]: *** [CMakeFiles/fatxfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by benpicco**
`_XOPEN_SOURCE` has to be set to [some number](https://stackoverflow.com/questions/5378778/what-does-d-xopen-source-do-mean?answertab=votes#tab-top) for `struct timespec` to be defined on newer systems. Let's do so to make it compile again.

fixes #3

### CODE REVIEW

File: src/fatx.h [hunk 1]
```diff
@@ -20,7 +20,11 @@
 #ifndef FATX_H
 #define FATX_H
 
-#define _XOPEN_SOURCE
+#if __STDC_VERSION__ >= 199901L
```
Comment (mborgerson) [inline src/fatx.h]: Why the branch? Just using 500 seems to work.

**Comment by mborgerson** [comment]
Thanks for the PR, please see comment in the code.

File: src/fatx.h (hunk 1 above)
Comment (benpicco) [reply src/fatx.h]: I found this bit on [Stackoverflow](https://stackoverflow.com/questions/3875197/linux-gcc-with-std-c99-complains-about-not-knowing-struct-timespec), but maybe it's better to keep it more deterministic.

On OS X a value of 600 is required [for strdup](https://gitlab.labs.nic.cz/kslany/libisds/commit/9343ebfc1447952a6c0c601f99147ef969cdddeb) to be available (which is not used in the code), yet I don't have such a system to see if there are any other quirks.

If you prefer only one value, I'd suggest 600 just to be sure.

**Comment by hesterbest123** [comment]
Thx, this helped me.

**Comment by ConnorRigby** [comment]
You can also use `-c11` instead of `-c99` to fix it

**Comment by patatetom** [comment]
@ConnorRigby - I'm not a compile regular : how do you call "-c11" ?

**Comment by ConnorRigby** [comment]
https://github.com/mborgerson/fatx/blob/master/CMakeLists.txt#L29 Change that to `-c11`

**Comment by patatetom** [comment]
@ConnorRigby - thanks !

**Comment by mborgerson** [comment]
Should be fixed now, thanks.
